<?php
/**
 * ====================================================================
 * TEMEL VERİTABANI ŞEMASI (sıfırdan kurulum)
 * ====================================================================
 * install.php tarafından boş veritabanına bir kez uygulanır. Diğer tüm
 * tablolar ve sütunlar ilk açılışta includes/functions.php → run_migrations()
 * ile otomatik oluşturulur.
 */

const INSTALL_SCHEMA_SQL = <<<'SQL'
CREATE TABLE IF NOT EXISTS roles (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_name VARCHAR(100), role_slug VARCHAR(100), description TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS permissions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, permission_key VARCHAR(100) UNIQUE, description VARCHAR(255), module VARCHAR(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS role_permissions (role_id INT UNSIGNED, permission_id INT UNSIGNED, PRIMARY KEY(role_id, permission_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS contacts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, type VARCHAR(30) DEFAULT 'client', company_title VARCHAR(200) NOT NULL, authorized_person VARCHAR(150), phone VARCHAR(50), email VARCHAR(150), tax_office VARCHAR(100), tax_number VARCHAR(50), id_number VARCHAR(20), iban VARCHAR(50), city VARCHAR(80), district VARCHAR(80), address TEXT, notes TEXT, balance DECIMAL(15,2) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id INT UNSIGNED NOT NULL, contact_id INT UNSIGNED NULL, full_name VARCHAR(150), email VARCHAR(150) UNIQUE, password VARCHAR(255), phone VARCHAR(50), avatar VARCHAR(255), status ENUM('active','inactive') DEFAULT 'active', last_login DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS projects (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, client_id INT UNSIGNED, project_code VARCHAR(50) UNIQUE, project_name VARCHAR(200), project_type VARCHAR(50), workflow_model ENUM('internal_full','external_edit_only','external_shoot_only','outsource_full','outsource_edit','outsource_shoot') DEFAULT 'internal_full', outsource_contact_id INT UNSIGNED NULL, status VARCHAR(30) DEFAULT 'pre_production', agreed_budget DECIMAL(15,2) DEFAULT 0, currency VARCHAR(10) DEFAULT 'TRY', start_date DATE NULL, deadline DATE NULL, description TEXT, created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES contacts(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS shoots (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, project_id INT UNSIGNED NOT NULL, title VARCHAR(200), shoot_date DATE, start_time TIME NULL, end_time TIME NULL, location_name VARCHAR(200), location_address TEXT, call_sheet_notes TEXT, FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS invoices (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_type ENUM('sales','purchase') NOT NULL, invoice_number VARCHAR(50), contact_id INT UNSIGNED NOT NULL, project_id INT UNSIGNED NULL, issue_date DATE, due_date DATE NULL, subtotal DECIMAL(15,2), vat_rate DECIMAL(5,2), vat_amount DECIMAL(15,2), withholding_rate VARCHAR(10) DEFAULT '0/10', withholding_amount DECIMAL(15,2) DEFAULT 0, stoppage_rate DECIMAL(5,2) DEFAULT 0, stoppage_amount DECIMAL(15,2) DEFAULT 0, grand_total DECIMAL(15,2), paid_amount DECIMAL(15,2) DEFAULT 0, payment_status ENUM('unpaid','partial','paid') DEFAULT 'unpaid', notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (contact_id) REFERENCES contacts(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS shoot_crew_gear (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, shoot_id INT UNSIGNED NOT NULL, contact_id INT UNSIGNED NULL, category VARCHAR(50), item_title VARCHAR(200), agreed_fee DECIMAL(15,2), currency VARCHAR(10), is_rebillable TINYINT DEFAULT 0, vat_rate DECIMAL(5,2) DEFAULT 20, vat_amount DECIMAL(15,2) DEFAULT 0, invoice_id INT UNSIGNED NULL, invoice_number VARCHAR(50) NULL, FOREIGN KEY (shoot_id) REFERENCES shoots(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS project_revisions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, project_id INT UNSIGNED NOT NULL, assigned_editor_id INT UNSIGNED NULL, version_title VARCHAR(150), preview_url VARCHAR(500), feedback_notes TEXT, status ENUM('in_progress','sent_to_client','revision_requested','approved') DEFAULT 'in_progress', billing_status ENUM('unbilled','invoiced','debited') DEFAULT 'unbilled', billing_fee DECIMAL(15,2) DEFAULT 0.00, invoice_id INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS accounts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, account_name VARCHAR(150), account_type ENUM('cash','bank') DEFAULT 'bank', currency VARCHAR(10), bank_name VARCHAR(150), iban VARCHAR(50), balance DECIMAL(15,2) DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS transactions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, account_id INT UNSIGNED NULL, contact_id INT UNSIGNED NULL, invoice_id INT UNSIGNED NULL, project_id INT UNSIGNED NULL, type ENUM('income','expense'), category VARCHAR(100), amount DECIMAL(15,2), transaction_date DATE, description TEXT, created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS project_types (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, type_key VARCHAR(50) NOT NULL UNIQUE, type_name VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS system_settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT, setting_group VARCHAR(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS personnel (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(80), last_name VARCHAR(80), identity_number VARCHAR(20), department VARCHAR(80), job_title VARCHAR(100), base_salary DECIMAL(15,2), start_date DATE NULL, iban VARCHAR(50), status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS payrolls (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, personnel_id INT UNSIGNED, period_month INT, period_year INT, base_salary DECIMAL(15,2), bonus DECIMAL(15,2), deductions DECIMAL(15,2), advance_deductions DECIMAL(15,2), net_paid DECIMAL(15,2), status VARCHAR(20), payment_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS advances (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, personnel_id INT UNSIGNED, amount DECIMAL(15,2), request_date DATE, status VARCHAR(30), reason VARCHAR(255), approved_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS equipment (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_name VARCHAR(150), category VARCHAR(30), serial_number VARCHAR(100), purchase_price DECIMAL(15,2), purchase_date DATE NULL, storage_location VARCHAR(150), status VARCHAR(30) DEFAULT 'in_office', assigned_user_id INT UNSIGNED NULL, current_project_id INT UNSIGNED NULL, rental_contact_id INT UNSIGNED NULL, rental_start_date DATE NULL, rental_end_date DATE NULL, rental_total_fee DECIMAL(15,2) DEFAULT 0.00, notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO roles (id, role_name, role_slug) VALUES (1,'Süper Admin','super_admin'),(2,'Yapımcı','producer'),(3,'Editör','editor'),(4,'Muhasebe','accountant');
INSERT INTO permissions (permission_key, description, module) VALUES
('projects.view','Projeleri gör','projects'),('projects.create','Proje oluştur','projects'),('projects.edit','Proje düzenle','projects'),('projects.delete','Proje sil','projects'),
('contacts.view','Carileri gör','contacts'),('contacts.create','Cari oluştur','contacts'),('contacts.edit','Cari düzenle','contacts'),('contacts.delete','Cari sil','contacts'),
('finance.view','Finans gör','finance'),('finance.invoices','Faturalar','finance'),('finance.taxes','Vergiler','finance'),('personnel.manage','Personel','personnel'),('settings.manage','Ayarlar','settings');
INSERT INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE permission_key IN ('projects.view','projects.edit');
INSERT INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE permission_key LIKE 'finance.%' OR permission_key='contacts.view';
SQL;
